export const URLS_PREFIX = {
  API: '/api',
  AUTHENTICATION: '/auth',
  SERVICO_OFERECIDO: '/servico-oferecido'
} as const;

export const SERVICO_OFERECIDO_URLS = {
  GET_ALL_SERVICOS_OFERECIDOS: `${URLS_PREFIX.SERVICO_OFERECIDO}/listar/`
};

export const AUTHENTICATION_URLS = {
  GET_TOKEN: `${URLS_PREFIX.AUTHENTICATION}/token/`,
  REFRESH_TOKEN: `${URLS_PREFIX.AUTHENTICATION}/token/refresh/`,
  VERIFY_TOKEN: `${URLS_PREFIX.AUTHENTICATION}/token/verify/`
};

export const URLS_TO_BE_IGNORED: string[] = [
  AUTHENTICATION_URLS.GET_TOKEN,
  AUTHENTICATION_URLS.REFRESH_TOKEN,
  AUTHENTICATION_URLS.VERIFY_TOKEN
];
