-- ========================================
-- V1: Criação das tabelas principais
-- Estoque e Agendamento
-- ========================================

-- Tabela de Produtos
CREATE TABLE PRODUTO (
    ID INT GENERATED ALWAYS AS IDENTITY NOT NULL,
    NOME VARCHAR(200) NOT NULL UNIQUE,
    ESTOQUE INT NOT NULL DEFAULT 0,
    PRECO DECIMAL(10, 2) NOT NULL,
    ESTOQUE_MINIMO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID)
);

-- Índices para Produto
CREATE INDEX IDX_PRODUTO_NOME ON PRODUTO(NOME);
CREATE INDEX IDX_PRODUTO_ESTOQUE ON PRODUTO(ESTOQUE);

-- Tabela de Movimentação de Estoque
CREATE TABLE MOVIMENTACAO_ESTOQUE (
    ID INT GENERATED ALWAYS AS IDENTITY NOT NULL,
    PRODUTO_ID INT NOT NULL,
    NOME_PRODUTO VARCHAR(200) NOT NULL,
    TIPO VARCHAR(50) NOT NULL,
    QUANTIDADE INT NOT NULL,
    ESTOQUE_ANTERIOR INT NOT NULL,
    ESTOQUE_ATUAL INT NOT NULL,
    DATA_HORA TIMESTAMP NOT NULL,
    OBSERVACAO VARCHAR(500),
    USUARIO_RESPONSAVEL VARCHAR(100),
    PRIMARY KEY (ID),
    FOREIGN KEY (PRODUTO_ID) REFERENCES PRODUTO(ID)
);

-- Índices para Movimentação de Estoque
CREATE INDEX IDX_MOVIMENTACAO_PRODUTO ON MOVIMENTACAO_ESTOQUE(PRODUTO_ID);
CREATE INDEX IDX_MOVIMENTACAO_DATA ON MOVIMENTACAO_ESTOQUE(DATA_HORA);
CREATE INDEX IDX_MOVIMENTACAO_TIPO ON MOVIMENTACAO_ESTOQUE(TIPO);

-- Tabela de Agendamentos
CREATE TABLE AGENDAMENTO (
    ID INT GENERATED ALWAYS AS IDENTITY NOT NULL,
    DATA_HORA TIMESTAMP NOT NULL,
    STATUS VARCHAR(20) NOT NULL,
    CLIENTE_ID INT NOT NULL,
    PROFISSIONAL_ID INT,
    SERVICO_ID INT NOT NULL,
    OBSERVACOES VARCHAR(500),
    PRIMARY KEY (ID)
);

-- Índices para Agendamento
CREATE INDEX IDX_AGENDAMENTO_DATA_HORA ON AGENDAMENTO(DATA_HORA);
CREATE INDEX IDX_AGENDAMENTO_CLIENTE ON AGENDAMENTO(CLIENTE_ID);
CREATE INDEX IDX_AGENDAMENTO_PROFISSIONAL ON AGENDAMENTO(PROFISSIONAL_ID);
CREATE INDEX IDX_AGENDAMENTO_STATUS ON AGENDAMENTO(STATUS);
CREATE INDEX IDX_AGENDAMENTO_CONFLITO ON AGENDAMENTO(PROFISSIONAL_ID, DATA_HORA, STATUS);

-- Comentários nas tabelas
COMMENT ON TABLE PRODUTO IS 'Cadastro de produtos disponíveis para venda';
COMMENT ON TABLE MOVIMENTACAO_ESTOQUE IS 'Histórico de todas as movimentações de estoque';
COMMENT ON TABLE AGENDAMENTO IS 'Registro de agendamentos de serviços';

-- Comentários nas colunas
COMMENT ON COLUMN MOVIMENTACAO_ESTOQUE.TIPO IS 'Tipo: ENTRADA, SAIDA, VENDA, AJUSTE, ESTOQUE_INICIAL, DESATIVACAO';
COMMENT ON COLUMN AGENDAMENTO.STATUS IS 'Status: PENDENTE, CONFIRMADO, CANCELADO, CONCLUIDO';
