FROM mysql:8.0

ENV MYSQL_DATABASE="arbearia_db"
ENV MYSQL_ROOT_PASSWORD="root"

# docker build -t barbearia-mysql:mysql .
# docker run -d -p 3306:3306 --name barbearia-mysql -e MYSQL_ROOT_PASSWORD=root barbearia-mysql:mysql