FROM mysql:9

ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_DATABASE=aerocenter

# 1. Build the container
# cd mysql
# docker build -t barbearia-mysql-development .

# 2. Run the container
# docker run --name mysql-barbearia -p 3307:3306 -d barbearia-mysql-development

# 3. After the first run is not necessary to build again, just start the container by...
# docker start mysql-barbearia