FROM mysql:8.1

ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_DATABASE=aerocenter

# 1. Build the container
# docker build -t aerocenter-mysql-development .

# 2. Run the container
# docker run --name mysql-aerocenter -p 3307:3306 -d aerocenter-mysql-development

# 3. After the first run
# docker start mysql-aerocenter